package com.example.wags.ui.common

import androidx.compose.animation.core.*
import androidx.compose.foundation.Canvas
import androidx.compose.foundation.background
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.Text
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.clip
import androidx.compose.ui.geometry.Offset
import androidx.compose.ui.graphics.Brush
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.Path
import androidx.compose.ui.graphics.StrokeCap
import androidx.compose.ui.graphics.StrokeJoin
import androidx.compose.ui.graphics.drawscope.DrawScope
import androidx.compose.ui.graphics.drawscope.Stroke
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp

// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
//  COHERENCE STRIP CHART
//
//  Scrolling coherence ratio chart that behaves like the RR/RMSSD strip charts.
//  Coherence samples arrive every ~5 seconds and are plotted at wall-clock time.
//  The chart scrolls smoothly at 60 fps via withFrameNanos.
//  Uses Catmull-Rom spline interpolation for smooth curves between sparse points.
// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

/** Default time window for coherence chart (60 seconds). */
private const val COHERENCE_WINDOW_MS = 60_000.0

/** Assumed cadence between raw coherence samples (the loop computes one every ~5 s). */
private const val SAMPLE_INTERVAL_MS = 5_000.0

/** Sub-point spacing used to densify the line (1 sub-point per second, like RR beats). */
private const val SUB_POINT_MS = 1_000.0

/**
 * A single coherence sample with its wall-clock time offset.
 */
data class TimedCoherence(val timeMs: Double, val value: Double)

/**
 * Holds the strip-chart state for coherence ratios.
 *
 * Coherence values arrive as a plain `List<Float>` history whose samples are
 * produced every ~[SAMPLE_INTERVAL_MS] (5 s). That cadence is far too slow for
 * a smooth scrolling strip chart: with only one point every 5 s the right edge
 * drifts a quarter of the window before the next update.
 *
 * To match the RR / RMSSD strip charts — which receive a new beat roughly
 * every second — point generation is driven by [tick], called every frame from
 * the Composable. [tick] emits a new point at the wall-clock cursor every
 * [SUB_POINT_MS] (≈1 s), holding the latest coherence value from [ingest].
 * The Catmull-Rom spline in the draw pass smooths the value transitions,
 * producing the same visual cadence and shimmer "surf" effect as the HR / HRV
 * charts.
 */
@Stable
class CoherenceStripChartState(private val windowMs: Double = COHERENCE_WINDOW_MS) {
    val samples = mutableStateListOf<TimedCoherence>()
    var started by mutableStateOf(false)
        private set
    var firstSampleWallMs: Long = 0L
        private set
    private var lastSourceSize = 0

    /** Most recent coherence value — updated by [ingest], read by [tick]. */
    private var currentValue = Double.NaN

    /** Wall-clock time of the last point emitted by [tick] (for throttling). */
    private var lastTickTime = 0.0

    /**
     * Accept new coherence samples from the ViewModel.
     *
     * Only records the latest value; the actual strip-chart points are
     * generated by [tick] at a fixed ~1 s cadence so the chart behaves
     * identically to the RR / RMSSD strip charts.
     */
    fun ingest(source: List<Float>, nowNanos: Long) {
        if (source.isEmpty()) return

        val wallNow = System.currentTimeMillis()
        if (!started) {
            started = true
            firstSampleWallMs = wallNow
        }

        val newCount = if (lastSourceSize == 0 && samples.isEmpty()) {
            source.size
        } else {
            (source.size - lastSourceSize).coerceAtLeast(0)
        }

        if (newCount > 0) {
            currentValue = source.last().toDouble()
            // Seed the very first point so tick() has something to extend from.
            if (samples.isEmpty()) {
                val wallTimeMs = (wallNow - firstSampleWallMs).toDouble()
                samples.add(TimedCoherence(wallTimeMs, currentValue))
                lastTickTime = wallTimeMs
            }
        }
        lastSourceSize = source.size
    }

    /**
     * Called every frame from the Composable. Emits a new point at the
     * wall-clock cursor every [SUB_POINT_MS] (≈1 s), holding the latest
     * coherence value. This makes the chart grow continuously toward the
     * right edge — exactly like the RR / RMSSD strip charts where a new
     * beat arrives every second — instead of sitting idle for a full 5 s
     * between raw coherence computations.
     */
    fun tick(cursorTimeMs: Double) {
        if (!started || samples.isEmpty() || currentValue.isNaN()) return
        if (cursorTimeMs - lastTickTime >= SUB_POINT_MS) {
            samples.add(TimedCoherence(cursorTimeMs, currentValue))
            lastTickTime = cursorTimeMs

            // Prune far-offscreen samples
            val cutoff = cursorTimeMs - windowMs * 2
            while (samples.size > 2 && samples.first().timeMs < cutoff) {
                samples.removeAt(0)
            }
        }
    }
}

/**
 * Scrolling coherence ratio strip chart.
 *
 * @param coherenceHistory List of coherence ratio samples from the ViewModel.
 * @param windowMs Time window in ms (default 60 s).
 * @param colors Colour scheme for the chart.
 * @param waitingText Text shown before enough data arrives.
 * @param modifier Standard Compose modifier.
 */
@Composable
fun CoherenceStripChart(
    coherenceHistory: List<Float>,
    modifier: Modifier = Modifier,
    windowMs: Double = COHERENCE_WINDOW_MS,
    colors: StripChartColors = StripChartColors(),
    waitingText: String = "awaiting data…"
) {
    val state = remember { CoherenceStripChartState(windowMs) }
    var cursorTimeMs by remember { mutableDoubleStateOf(0.0) }

    // Fingerprint must not truncate the float to Long — two close coherence
    // values (e.g. 2.04 and 2.03) would otherwise collide and skip an update.
    val fingerprint = remember(coherenceHistory) {
        if (coherenceHistory.isEmpty()) 0L
        else (coherenceHistory.size.toLong() shl 32) xor
             coherenceHistory.last().toBits().toLong()
    }
    LaunchedEffect(fingerprint) { state.ingest(coherenceHistory, System.nanoTime()) }

    // Pure wall-clock cursor: advances every frame at exactly real-time speed.
    // Also extends the line toward the cursor every ~1 s (SUB_POINT_MS) so the
    // right edge stays pinned near the right side of the screen — identical to
    // the RR / RMSSD strip charts where a new beat arrives every second.
    LaunchedEffect(Unit) {
        while (true) {
            withFrameNanos { _ ->
                if (state.started) {
                    val cursor = (System.currentTimeMillis() - state.firstSampleWallMs).toDouble()
                    cursorTimeMs = cursor
                    state.tick(cursor)
                }
            }
        }
    }

    CoherenceStripChartShell(
        samples = state.samples,
        cursorTimeMs = cursorTimeMs,
        windowMs = windowMs,
        colors = colors,
        waitingText = waitingText,
        defaultMinY = 0.0,
        defaultMaxY = 5.0,
        minYRange = 1.0,
        modifier = modifier
    )
}

/**
 * Internal shell that renders the coherence strip chart using the same
 * approach as RR/RMSSD strip charts (Catmull-Rom spline, left-edge fade).
 */
@Composable
private fun CoherenceStripChartShell(
    samples: List<TimedCoherence>,
    cursorTimeMs: Double,
    windowMs: Double,
    colors: StripChartColors,
    waitingText: String,
    defaultMinY: Double,
    defaultMaxY: Double,
    minYRange: Double,
    modifier: Modifier = Modifier
) {
    val infiniteTransition = rememberInfiniteTransition(label = "chart_shimmer")
    val shimmerPhase by infiniteTransition.animateFloat(
        initialValue = 0f, targetValue = 1f,
        animationSpec = infiniteRepeatable(
            tween(3000, easing = LinearEasing), RepeatMode.Restart
        ),
        label = "shimmer"
    )

    val targetMin = if (samples.isEmpty()) defaultMinY else samples.minOf { it.value }
    val targetMax = if (samples.isEmpty()) defaultMaxY else samples.maxOf { it.value }
    val range = (targetMax - targetMin).coerceAtLeast(minYRange)
    val animMin by animateFloatAsState(
        targetValue = (targetMin - range * 0.15).toFloat(),
        animationSpec = tween(600, easing = LinearOutSlowInEasing), label = "y_min"
    )
    val animMax by animateFloatAsState(
        targetValue = (targetMax + range * 0.15).toFloat(),
        animationSpec = tween(600, easing = LinearOutSlowInEasing), label = "y_max"
    )

    Box(
        modifier = modifier
            .clip(RoundedCornerShape(12.dp))
            .background(
                Brush.verticalGradient(
                    listOf(colors.bgDark, colors.bgMid.copy(alpha = 0.3f), colors.bgDark)
                )
            )
    ) {
        if (samples.size >= 2) {
            val snap = samples.toList()
            val cursor = cursorTimeMs
            Canvas(
                modifier = Modifier
                    .fillMaxSize()
                    .padding(horizontal = 8.dp, vertical = 8.dp)
            ) {
                drawCoherenceStripChart(
                    samples = snap,
                    cursorTimeMs = cursor,
                    windowMs = windowMs,
                    shimmerPhase = shimmerPhase,
                    paddedMin = animMin.toDouble(),
                    paddedMax = animMax.toDouble(),
                    lineColor = colors.lineColor,
                    dotColor = colors.dotColor,
                    glowColor = colors.glowColor,
                    bgDark = colors.bgDark
                )
            }
        } else {
            Box(modifier = Modifier.fillMaxSize(), contentAlignment = Alignment.Center) {
                Text(
                    waitingText,
                    style = MaterialTheme.typography.bodySmall,
                    color = colors.waitingTextColor.copy(alpha = 0.5f),
                    letterSpacing = 2.sp
                )
            }
        }
    }
}

// ── Drawing ─────────────────────────────────────────────────────────────────

private fun DrawScope.drawCoherenceStripChart(
    samples: List<TimedCoherence>,
    cursorTimeMs: Double,
    windowMs: Double,
    shimmerPhase: Float,
    paddedMin: Double,
    paddedMax: Double,
    lineColor: Color,
    dotColor: Color,
    glowColor: Color,
    bgDark: Color
) {
    if (samples.size < 2) return
    val w = size.width
    val h = size.height
    val yRange = (paddedMax - paddedMin).coerceAtLeast(1.0)
    val windowStart = cursorTimeMs - windowMs

    fun xAt(t: Double) = ((t - windowStart) / windowMs * w).toFloat()
    fun yAt(v: Double) = h - ((v - paddedMin) / yRange * h).toFloat()

    // Keep all samples that fall within the visible window (left edge with 2 s look-behind for
    // smooth entry). There is intentionally NO upper-bound filter on cursorTimeMs.
    val visible = samples.filter { it.timeMs >= windowStart - 2000 }
    if (visible.size < 2) return
    val pts = visible.map { Offset(xAt(it.timeMs), yAt(it.value)) }

    // Draw zone threshold lines
    val highY = (h - ((3.0 - paddedMin) / yRange * h).toFloat()).coerceIn(0f, h)
    val medY = (h - ((1.0 - paddedMin) / yRange * h).toFloat()).coerceIn(0f, h)
    
    drawLine(
        color = lineColor.copy(alpha = 0.3f),
        start = Offset(0f, highY),
        end = Offset(w.toFloat(), highY),
        strokeWidth = 1.dp.toPx()
    )
    drawLine(
        color = lineColor.copy(alpha = 0.2f),
        start = Offset(0f, medY),
        end = Offset(w.toFloat(), medY),
        strokeWidth = 1.dp.toPx()
    )

    // Glow line (wider, dimmer)
    val glowPath = Path()
    buildCatmullRomPath(glowPath, pts)
    drawPath(
        glowPath, glowColor.copy(alpha = 0.15f),
        style = Stroke(width = 6.dp.toPx(), cap = StrokeCap.Round, join = StrokeJoin.Round)
    )

    // Main line
    val mainPath = Path()
    buildCatmullRomPath(mainPath, pts)
    drawPath(
        mainPath, lineColor,
        style = Stroke(width = 1.5.dp.toPx(), cap = StrokeCap.Round, join = StrokeJoin.Round)
    )

    // Dots at each data point
    pts.forEach { pt ->
        if (pt.x < -10f || pt.x > w + 10f) return@forEach
        val nx = (pt.x / w).coerceIn(0f, 1f)
        val fade = if (nx < 0.15f) nx / 0.15f else 1f
        val dist = kotlin.math.abs(nx - shimmerPhase)
        val boost = (1f - (dist * 4f).coerceIn(0f, 1f)) * 0.4f
        drawCircle(
            dotColor.copy(alpha = (0.3f + boost) * fade),
            radius = (1.8f + boost * 2f).dp.toPx(),
            center = pt
        )
    }

    // Left-edge fade overlay — fall back to the standard dark base when the
    // caller set bgDark = Transparent (coherence charts sit inside a parent
    // Box with its own gradient, so bgDark is transparent, but the fade still
    // needs an opaque base to create the line fade-out + shimmer "surf"
    // effect that the HR / HRV charts have).
    val fadeBase = if (bgDark.alpha > 0f) bgDark else Color(0xFF0A0A0A)
    drawRect(
        brush = Brush.horizontalGradient(
            colors = listOf(fadeBase, fadeBase.copy(alpha = 0f)),
            startX = 0f, endX = w * 0.12f
        ),
        size = size
    )
}

// ── Catmull-Rom spline ──────────────────────────────────────────────────────

/**
 * Builds a Catmull-Rom spline path through the given points.
 * Produces a smooth curve that passes through every data point.
 */
private fun buildCatmullRomPath(path: Path, points: List<Offset>) {
    if (points.size < 2) return
    path.moveTo(points[0].x, points[0].y)
    if (points.size == 2) { path.lineTo(points[1].x, points[1].y); return }

    val ext = buildList {
        add(Offset(
            points[0].x - (points[1].x - points[0].x),
            points[0].y - (points[1].y - points[0].y)
        ))
        addAll(points)
        add(Offset(
            points.last().x + (points.last().x - points[points.size - 2].x),
            points.last().y + (points.last().y - points[points.size - 2].y)
        ))
    }
    val tension = 0.5f
    val segs = 12
    for (i in 1 until ext.size - 2) {
        val p0 = ext[i - 1]; val p1 = ext[i]; val p2 = ext[i + 1]; val p3 = ext[i + 2]
        for (s in 1..segs) {
            val t = s.toFloat() / segs; val t2 = t * t; val t3 = t2 * t
            val x = tension * (
                (2 * p1.x) +
                (-p0.x + p2.x) * t +
                (2 * p0.x - 5 * p1.x + 4 * p2.x - p3.x) * t2 +
                (-p0.x + 3 * p1.x - 3 * p2.x + p3.x) * t3
            )
            val y = tension * (
                (2 * p1.y) +
                (-p0.y + p2.y) * t +
                (2 * p0.y - 5 * p1.y + 4 * p2.y - p3.y) * t2 +
                (-p0.y + 3 * p1.y - 3 * p2.y + p3.y) * t3
            )
            path.lineTo(x, y)
        }
    }
}
